# Generated by Django 4.1.6 on 2023-02-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название альбома')),
                ('year_of_issue', models.IntegerField(verbose_name='Год выпуска альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
            },
        ),
        migrations.CreateModel(
            name='AlbumSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='Порядковый номер песни в альбоме')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discography_api.album', verbose_name='Альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discography_api.song', verbose_name='Песня')),
            ],
            options={
                'verbose_name': 'Песня в альбоме',
                'verbose_name_plural': 'Песни в альбоме',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discography_api.performer', verbose_name='Исполнитель'),
        ),
    ]
